// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MOG_BossHP","status":false,"description":"(v1.0) Apresenta um medidor de HP para os chefes.","parameters":{"Shake Effect":"true","HP Number Visible":"true","Show Face":"true","Slant Animation":"true","Flow Speed":"4","Name Font Size":"18","Layout X-Axis":"150","Layout Y-Axis":"10","Name X-Axis":"36","Name Y-Axis":"23","Face X-Axis":"-50","Face Y-Axis":"10","Meter X-Axis":"22","Meter Y-Axis":"28","Number X-Axis":"460","Number Y-Axis":"32","Number Percentage":"true","Show States":"true","States Max":"8","States X-axis":"50","States Y-axis":"-8"}},
{"name":"Change Battle Mode (MV)","status":false,"description":"Allows side view and front view battles in the same game","parameters":{}},
{"name":"Cecilia_NumericalPad","status":false,"description":"A numerical pad window for RMMV.","parameters":{"Window X Position":"0","Window Y Position":"210"}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"EnemyGauge","status":true,"description":"Displays the enemy's HP gauge at specific times.","parameters":{"chaseEnemy":"false","gaugeStyle":"default1","displayTiming":"affectedStatus","iconStyle":"sync","gaugePosition":"center","gaugeOffsetY":"80","iconOffsetY":"0","gaugeWidth":"128","gaugeHeight":"8","lineWidth":"1","waitDuration":"128","fadeDuration":"10","smoothness":"15","damagePosition":"center","damageOffsetY":"0"}}
];
